name: Go

on:
  push:
    branches: [ feature/ci ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build windows amd64
      run: go build -o ../../bin/ooops_win_amd64.exe
      working-directory: cmd/bot
      env:
        GOOS: windows
        GOARCH: amd64

    - name: Build linux amd64
      run: go build -o ../../bin/ooops_linux_amd64
      working-directory: cmd/bot
      env:
        GOOS: linux
        GOARCH: amd64

    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
