name: Build binaries

on:
  push:
    branches: [ feature/ci ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build windows amd64
      run: go build -o ../../bin/ooops.exe
      working-directory: cmd/bot
      env:
        GOOS: windows
        GOARCH: amd64
    - name: Create windows zip
      uses: papeloto/action-zip@v1
      with:
        files: data/ bin/ooops.exe
        recursive: true
        dest: ooops_windows_amd64.zip
          
    - name: Build linux amd64
      run: go build -o ../../bin/ooops
      working-directory: cmd/bot
      env:
        GOOS: linux
        GOARCH: amd64
    - name: Create linux zip 
      uses: papeloto/action-zip@v1
      with:
        files: data/ bin/ooops
        recursive: true
        dest: ooops_linux_amd64.zip

    - name: Generate release name
      uses: thclark/coolname-generator-action@main
      id: generator
      with:
        separator: "_"
        length: "2"
        style: "lowerCase"
  
    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.generator.outputs.name }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ooops_linux_amd64.zip
        asset_name: ooops_linux_amd64.zip
        asset_content_type: application/zip

    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ooops_windows_amd64.zip
        asset_name: ooops_windows_amd64.zip
        asset_content_type: application/zip
